import type { Equipment, MaintenanceTeam, MaintenanceRequest, Technician } from "./types"

export const technicians: Technician[] = [
  { id: "t1", name: "John Miller", email: "john@company.com", avatar: "/male-technician.png", teamId: "team1" },
  { id: "t2", name: "Sarah Chen", email: "sarah@company.com", avatar: "/female-engineer-working.png", teamId: "team1" },
  {
    id: "t3",
    name: "Mike Rodriguez",
    email: "mike@company.com",
    avatar: "/male-mechanic.jpg",
    teamId: "team2",
  },
  { id: "t4", name: "Emily Davis", email: "emily@company.com", avatar: "/female-technician.png", teamId: "team2" },
  { id: "t5", name: "Alex Kim", email: "alex@company.com", avatar: "/person-it-support.jpg", teamId: "team3" },
  { id: "t6", name: "Lisa Wang", email: "lisa@company.com", avatar: "/female-developer.png", teamId: "team3" },
]

export const maintenanceTeams: MaintenanceTeam[] = [
  {
    id: "team1",
    name: "Electricians",
    specialization: "Electrical systems and wiring",
    members: technicians.filter((t) => t.teamId === "team1"),
  },
  {
    id: "team2",
    name: "Mechanics",
    specialization: "Mechanical equipment and machinery",
    members: technicians.filter((t) => t.teamId === "team2"),
  },
  {
    id: "team3",
    name: "IT Support",
    specialization: "Computers and digital systems",
    members: technicians.filter((t) => t.teamId === "team3"),
  },
]

export const equipment: Equipment[] = [
  {
    id: "e1",
    name: "CNC Machine A1",
    serialNumber: "CNC-2023-001",
    category: "machinery",
    department: "Production",
    location: "Building A, Floor 1",
    purchaseDate: "2023-01-15",
    warrantyExpiry: "2026-01-15",
    maintenanceTeamId: "team2",
    defaultTechnicianId: "t3",
    isActive: true,
  },
  {
    id: "e2",
    name: "Industrial Printer 01",
    serialNumber: "PRT-2022-045",
    category: "machinery",
    department: "Production",
    location: "Building A, Floor 2",
    purchaseDate: "2022-06-20",
    warrantyExpiry: "2025-06-20",
    maintenanceTeamId: "team1",
    defaultTechnicianId: "t1",
    isActive: true,
  },
  {
    id: "e3",
    name: "Forklift FL-23",
    serialNumber: "FLK-2021-023",
    category: "vehicle",
    department: "Warehouse",
    location: "Warehouse B",
    purchaseDate: "2021-03-10",
    maintenanceTeamId: "team2",
    defaultTechnicianId: "t4",
    isActive: true,
  },
  {
    id: "e4",
    name: "Server Rack 01",
    serialNumber: "SRV-2023-001",
    category: "computer",
    department: "IT",
    location: "Data Center",
    purchaseDate: "2023-08-01",
    warrantyExpiry: "2028-08-01",
    maintenanceTeamId: "team3",
    defaultTechnicianId: "t5",
    isActive: true,
  },
  {
    id: "e5",
    name: "Laptop - Marketing",
    serialNumber: "LPT-2024-102",
    category: "computer",
    department: "Marketing",
    assignedTo: "Jane Smith",
    location: "Building B, Floor 3",
    purchaseDate: "2024-02-15",
    warrantyExpiry: "2027-02-15",
    maintenanceTeamId: "team3",
    defaultTechnicianId: "t6",
    isActive: true,
  },
  {
    id: "e6",
    name: "Welding Station W2",
    serialNumber: "WLD-2020-002",
    category: "tool",
    department: "Production",
    location: "Building A, Workshop",
    purchaseDate: "2020-11-20",
    maintenanceTeamId: "team2",
    defaultTechnicianId: "t3",
    isActive: true,
  },
  {
    id: "e7",
    name: "HVAC Unit - Main",
    serialNumber: "HVC-2019-001",
    category: "machinery",
    department: "Facilities",
    location: "Rooftop",
    purchaseDate: "2019-05-15",
    maintenanceTeamId: "team1",
    defaultTechnicianId: "t2",
    isActive: true,
  },
  {
    id: "e8",
    name: "Delivery Van V1",
    serialNumber: "VAN-2022-001",
    category: "vehicle",
    department: "Logistics",
    location: "Parking Lot A",
    purchaseDate: "2022-09-01",
    warrantyExpiry: "2025-09-01",
    maintenanceTeamId: "team2",
    defaultTechnicianId: "t4",
    isActive: true,
  },
]

export const maintenanceRequests: MaintenanceRequest[] = [
  {
    id: "r1",
    subject: "Oil leak detected",
    description: "Hydraulic oil leaking from main cylinder",
    type: "corrective",
    stage: "new",
    equipmentId: "e1",
    maintenanceTeamId: "team2",
    priority: "high",
    createdAt: "2024-12-20T09:00:00Z",
    updatedAt: "2024-12-20T09:00:00Z",
    isOverdue: true,
  },
  {
    id: "r2",
    subject: "Printer paper jam frequent",
    description: "Paper jams occurring multiple times daily",
    type: "corrective",
    stage: "new",
    equipmentId: "e2",
    maintenanceTeamId: "team1",
    priority: "medium",
    createdAt: "2024-12-25T14:30:00Z",
    updatedAt: "2024-12-25T14:30:00Z",
    isOverdue: false,
  },
  {
    id: "r3",
    subject: "Forklift battery replacement",
    description: "Battery not holding charge",
    type: "corrective",
    stage: "in-progress",
    equipmentId: "e3",
    maintenanceTeamId: "team2",
    assignedTechnicianId: "t4",
    priority: "high",
    createdAt: "2024-12-22T08:00:00Z",
    updatedAt: "2024-12-26T10:00:00Z",
    isOverdue: false,
  },
  {
    id: "r4",
    subject: "Server maintenance check",
    description: "Quarterly server inspection and cleaning",
    type: "preventive",
    stage: "in-progress",
    equipmentId: "e4",
    maintenanceTeamId: "team3",
    assignedTechnicianId: "t5",
    scheduledDate: "2024-12-28T09:00:00Z",
    priority: "medium",
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-27T08:00:00Z",
    isOverdue: false,
  },
  {
    id: "r5",
    subject: "Laptop screen flickering",
    description: "Display intermittently flickering",
    type: "corrective",
    stage: "repaired",
    equipmentId: "e5",
    maintenanceTeamId: "team3",
    assignedTechnicianId: "t6",
    priority: "low",
    createdAt: "2024-12-18T11:00:00Z",
    updatedAt: "2024-12-24T16:00:00Z",
    completedAt: "2024-12-24T16:00:00Z",
    duration: 45,
    isOverdue: false,
  },
  {
    id: "r6",
    subject: "Welding torch calibration",
    description: "Annual calibration required",
    type: "preventive",
    stage: "new",
    equipmentId: "e6",
    maintenanceTeamId: "team2",
    scheduledDate: "2024-12-30T10:00:00Z",
    priority: "medium",
    createdAt: "2024-12-20T09:00:00Z",
    updatedAt: "2024-12-20T09:00:00Z",
    isOverdue: false,
  },
  {
    id: "r7",
    subject: "HVAC filter replacement",
    description: "Monthly filter change",
    type: "preventive",
    stage: "repaired",
    equipmentId: "e7",
    maintenanceTeamId: "team1",
    assignedTechnicianId: "t2",
    scheduledDate: "2024-12-25T08:00:00Z",
    priority: "low",
    createdAt: "2024-12-10T09:00:00Z",
    updatedAt: "2024-12-25T12:00:00Z",
    completedAt: "2024-12-25T12:00:00Z",
    duration: 30,
    isOverdue: false,
  },
  {
    id: "r8",
    subject: "Van brake inspection",
    description: "Squeaking noise when braking",
    type: "corrective",
    stage: "scrap",
    equipmentId: "e8",
    maintenanceTeamId: "team2",
    assignedTechnicianId: "t3",
    priority: "critical",
    createdAt: "2024-12-19T07:00:00Z",
    updatedAt: "2024-12-26T14:00:00Z",
    isOverdue: false,
  },
  {
    id: "r9",
    subject: "CNC spindle maintenance",
    description: "Bi-annual spindle inspection",
    type: "preventive",
    stage: "new",
    equipmentId: "e1",
    maintenanceTeamId: "team2",
    scheduledDate: "2025-01-05T09:00:00Z",
    priority: "medium",
    createdAt: "2024-12-26T09:00:00Z",
    updatedAt: "2024-12-26T09:00:00Z",
    isOverdue: false,
  },
  {
    id: "r10",
    subject: "Electrical panel inspection",
    description: "Annual safety inspection",
    type: "preventive",
    stage: "in-progress",
    equipmentId: "e2",
    maintenanceTeamId: "team1",
    assignedTechnicianId: "t1",
    scheduledDate: "2024-12-27T10:00:00Z",
    priority: "high",
    createdAt: "2024-12-20T08:00:00Z",
    updatedAt: "2024-12-27T10:30:00Z",
    isOverdue: false,
  },
]

// Helper functions
export function getEquipmentById(id: string): Equipment | undefined {
  return equipment.find((e) => e.id === id)
}

export function getTeamById(id: string): MaintenanceTeam | undefined {
  return maintenanceTeams.find((t) => t.id === id)
}

export function getTechnicianById(id: string): Technician | undefined {
  return technicians.find((t) => t.id === id)
}

export function getRequestsByEquipment(equipmentId: string): MaintenanceRequest[] {
  return maintenanceRequests.filter((r) => r.equipmentId === equipmentId)
}

export function getOpenRequestsCount(equipmentId: string): number {
  return maintenanceRequests.filter(
    (r) => r.equipmentId === equipmentId && r.stage !== "repaired" && r.stage !== "scrap",
  ).length
}
